# The cost of getting a player's skull, in experience points
xp-cost: 100

history:
  # Whether to enable the name history feature.
  # If this is disabled, you do not need a database.
  enabled: true

database:
  # The type of database to use. Can be "sqlite", "mysql", or "postgresql".
  type: sqlite
  # The maximum number of connections to the database.
  max-connections: 10

  # Settings for PostgreSQL.
  postgresql:
    name: "skuld_names"
    username: "postgres"
    password: "password"

  # Settings for MySQL.
  mysql:
    name: "skuld_names"
    username: "root"
    password: "password"

